version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-west-1:1234567:task-definition/haproxy_group:48"
        LoadBalancerInfo:
          ContainerName: "haproxy_container"
          ContainerPort: 80
        CapacityProviderStrategy:
          - CapacityProvider: "haproxy-stage_capacity_provider"
            Base: 0
            Weight: 1
